### ISSUE TITLE
Building errors in Xcode 7.0.1 and 8

### ISSUE THREAD

**Issue by wilferraz** [SiliconLabs/thunderboard-ios#1]
Without converting the Swift version I got the following error:

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

After converting it to the Swift version 3, I got other 15 buildtime errors like the following:

Expected expression in list of expressions

Consecutive declarations on a line must be separated by ';'

Expected declaration

**Comment by sparrowapps** [comment]
Convert Swift version 2.3

ButtonSpinner.swift
class ButtonAnimationTrackLayer: CALayer , CAAnimationDelegate {

comment 
//override func animationDidStop(anim: CAAnimation, finished flag: Bool) {
// ...
//}

rand() / random() 
to
arc4random()

build OK

**Comment by wilferraz** [comment]
Sorry for the late reply but thank you. I did it and it worked all right. The key is to use version 2.3 and resolve the errors as they appear.
Will
