### ISSUE TITLE
Setting up Firebase

### ISSUE THREAD

**Issue by AndyIbanez** [SiliconLabs/thunderboard-ios#2]
Hey guys.

I'm a complete noob when it comes to Firebase. I want to enable Firebase support to do a quick testing of a few things.

I'd appreciate it if you guys provided a few more instructions to set Firebase up. The `README.md` doesn't say anything beyond "modify ApplicationConfig". What I need to know is how to get those values.

So let's start.

On my Firebase project Settings page, I have only found "Web API Key" and "Project ID". I can't really find the values I need for the Config file.

~~Is `HockeyToken` actually needed? The README states that if the `ApplicationConfig` class has no values, streaming won't be enabled. I'm not sure if this property is an exception to that rule. I feel like it should be since crash reporting shouldn't be directly relevant with Hockey.~~ 

After reading the README for a second time, I determined that HockeyToken is not needed.

How do I go around about getting `FirebaseIoHost`, ` FirebaseDemoHost`, and `FirebaseToken`? Again, I'm a noob when it comes to Firebase so I'm not familiar with it at all.

Thanks for your time.

**Comment by AndyIbanez** [comment]
I was able to find the IO host in the "Database" tab, but still searching for the other two (`FirebaseDemoHost` and `FirebaseToken`). Any help to get these two would be much appreciated.

**Comment by abitofalchemy** [comment]
In Xcode 8.2.1 after setting up an account on Firebase, added `import Firebase` to the AppDelegate and `FIRApp.configure()` to function `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {` ... but I still get error: Use of undeclared type 'Firebase' DemoStreamingConnection. 

What else can I do to get Firebase working with the app so I stream the raw values of my sensors?

**Comment by silabs-tiago** [comment]
The cloud streaming feature was temporarily disabled from the app.
