### ISSUE TITLE
Xcode Error

### ISSUE THREAD

**Issue by auwilld** [SiliconLabs/thunderboard-ios#6]
WYPopoverController.h file not found but does exist 

 error generated.
<unknown>:0: error: failed to emit precompiled header

Any reason why this would happen

**Comment by silabs-tiago** [comment]
Which file are you using to build - Thunderboard.xcodeproj or Thunderboard.xcworkspace ?

Error logs point out you are building from the former, but we use an external libraries so you have to build from the workspace file Thunderboard.xcworkspace (which contains Pods project inside).

**Comment by auwilld** [comment]
Hi Tiago,

Thanks, yes was compiling the project file.

Sorted, working

Thanks again

Kind Regards

Des

**Comment by silabs-tiago** [comment]
Thanks for confirming. I'm marking this issue as closed.
